### ISSUE TITLE
Question about canvas and viewport

### ISSUE THREAD

**Issue by Yuzuki-N** [ggambetta/computer-graphics-from-scratch#21]
Viewport seems to be a larger canvas. Do they have the same z-axis value?
![image](https://user-images.githubusercontent.com/59171699/138079034-b3e07078-8019-4816-a174-a5cbcd3f4727.png)

**Comment by ggambetta** [comment]
> Viewport seems to be a larger canvas.

The units are also different; the canvas is in pixels, the viewport is in world units.

> Do they have the same z-axis value?

The canvas doesn't have a z-axis, because it's a 2D collection of pixels. The z coordinate of every point of the viewport is the same, _d_, defined as the distance between the camera (fixed at the origin) and the projection plane.

**Comment by ggambetta** [comment]
May I suggest you read the [Basic Assumptions](https://gabrielgambetta.com/computer-graphics-from-scratch/02-basic-raytracing.html#basic-assumptions) section? It explains all this in detail.
